"""The switch from passlib to argon2-cffi must not strand existing password hashes."""
import importlib.util
import json
import re
from pathlib import Path

import pytest

from auth import passwords
from db import db

ROOT = Path(__file__).resolve().parents[1]
# Generated by passlib 1.7.4 with the exact CryptContext auth/passwords.py used before the switch.
LEGACY = json.loads((ROOT / "tests" / "fixtures" / "passlib_hashes.json").read_text(encoding="utf-8"))


@pytest.mark.parametrize("name", sorted(LEGACY["hashes"]))
def test_hashes_written_by_passlib_still_verify(app, name):
    stored = LEGACY["hashes"][name]

    assert passwords.verify_password(LEGACY["password"], stored)
    assert not passwords.verify_password(LEGACY["password"] + "!", stored)


def test_a_passlib_hash_logs_in_and_is_upgraded_to_the_current_parameters(client, make_org, login):
    _, user = make_org("alpha")
    user.password_hash = LEGACY["hashes"]["production_params"]
    db.session.commit()
    assert passwords.needs_rehash(user.password_hash)  # the test suite runs with different parameters

    assert login(client, user.email, LEGACY["password"]).status_code == 302

    db.session.refresh(user)
    assert user.password_hash != LEGACY["hashes"]["production_params"]
    assert not passwords.needs_rehash(user.password_hash)
    assert passwords.verify_password(LEGACY["password"], user.password_hash)


def test_new_hashes_are_argon2id_with_the_configured_parameters(app):
    assert re.match(r"\$argon2id\$v=19\$m=1024,t=1,p=1\$", passwords.hash_password("a sufficiently long passphrase"))


@pytest.mark.parametrize(
    "stored",
    [
        None,
        "",
        "not a hash",
        "$argon2id$v=19$m=1024,t=1,p=1$bad$bad",
        "$2b$12$C6UzMDM.H6dfI/f/IKcEeO5L9rpXSWpybPSRvDOfSeS3.ZWM/gT5K",
    ],
)
def test_malformed_or_foreign_hashes_never_verify(app, stored):
    assert passwords.verify_password("anything at all", stored) is False


def test_passlib_is_no_longer_used():
    assert importlib.util.find_spec("passlib") is None
    assert "passlib" not in (ROOT / "requirements.txt").read_text(encoding="utf-8")
    importers = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*.py")
        if ".venv" not in path.relative_to(ROOT).parts
        and re.search(r"^\s*(?:import|from)\s+passlib\b", path.read_text(encoding="utf-8"), re.MULTILINE)
    ]
    assert importers == []
