"""initial multi-tenant schema

Revision ID: cb67422390af
Revises: 
Create Date: 2026-09-13 18:26:20.995541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb67422390af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organisations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('owner', 'staff', 'viewer', name='user_role', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invite_token_hash', sa.String(length=64), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_users_organisation_id_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('invite_token_hash', name=op.f('uq_users_invite_token_hash'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_audit_events_organisation_id_organisations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_org_created', ['organisation_id', 'created_at'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('training', 'prediction', 'actual', name='dataset_kind', create_constraint=True), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_names', sa.JSON(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_datasets_organisation_id_organisations')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_datasets_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_datasets_storage_key'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index('ix_datasets_org_kind_uploaded', ['organisation_id', 'kind', 'uploaded_at'], unique=False)

    op.create_table('model_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm_name', sa.String(length=100), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_importances', sa.JSON(), nullable=False),
    sa.Column('model_comparison', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('trained_by', sa.Uuid(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_model_artifacts_organisation_id_organisations')),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], name=op.f('fk_model_artifacts_trained_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_artifacts')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_model_artifacts_storage_key'))
    )
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_artifacts_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index('uq_model_artifacts_one_active_per_org', ['organisation_id'], unique=True, postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.drop_index('uq_model_artifacts_one_active_per_org', postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
        batch_op.drop_index(batch_op.f('ix_model_artifacts_organisation_id'))

    op.drop_table('model_artifacts')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index('ix_datasets_org_kind_uploaded')

    op.drop_table('datasets')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_org_created')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organisation_id'))

    op.drop_table('users')
    op.drop_table('organisations')
    # PostgreSQL keeps enum types after their tables are dropped.
    sa.Enum(name='dataset_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
